name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
  GCP_SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Docker configuration
      run: |-
        echo ${{secrets.GCP_SA_KEY}} > gcloud-api-key.json
        gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

    - name: Build Docker Image
      run: docker build -t ${{ env.GCP_REGION }}-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA .

    - name: Push Docker Image to Container Registry
      run: docker push ${{ env.GCP_REGION }}-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.GCP_SERVICE_NAME }}
        region: ${{ env.GCP_REGION }}
        image: ${{ env.GCP_REGION }}-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
        env_vars: |
          GCS_BUCKET_NAME=${{ env.GCS_BUCKET_NAME }}
        allow_unauthenticated: true