name: Mirror to Artifact Registry

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure Git
      run: |-
        git config --global user.email "sang.ahn.94@gmail.com"
        git config --global user.name "Sang Ahn"

    - name: Push to Artifact Registry
      run: |-
        git remote add gcp us-west1-docker.pkg.dev/senator-stock-rag-chatbot/senator-stock-rag-chatbot
        git push gcp --all